# Não precisamos de especificar a URL, username ou password.
# O Spring Boot vai detetar a variável de ambiente DATABASE_URL fornecida pela Render.

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
