# Configuração da conexão com o banco de dados PostgreSQL
# A URL completa é fornecida pela Render. Nós apenas adicionamos o prefixo "jdbc:"
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL}

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
